### ISSUE TITLE
Missing ‘echars’ module

### ISSUE THREAD

**Issue by isscc** [k-water/electron-filesystem#5]
issue: 执行"npm run dev" 会出错  Module not found: Error: Can't resolve 'echarts'
fix: package.json 中添加echarts 依赖后，可以正常运行。

**Comment by k-water** [comment]
这个项目用的v-charts哦 @isscc

**Comment by xql279671304** [comment]
好像v-charts1.15.1这个版本安装不上，直接重新npm install v-charts@1.15 -save 可以安装上，出来的版本是 1.15.6，能正常运行

**Comment by fakaka** [comment]
v-charts 好像没有正确安装echarts

**Comment by fakaka** [comment]
v-charts 是基于 echarts 的，
v-charts  的文档

## Install
```
npm i v-charts echarts -S
```

好像就是都要装才行

**Comment by LSL1618** [comment]
将`package.json`文件中的`"v-charts": "^1.15.1"`改为`"v-charts": "~1.15.6"`，再`npm install`后`npm run dev`就好了。

**Comment by qiufeihong2018** [comment]
脑壳疼
